// 🧪 [INÍCIO: TESTE - NOTES CHECKLIST NUMBERS]
/*
 * Portado automaticamente de produtividade-ferrramenta/tests/notes_checklist_numbers.cjs por tools/portar-testes.cjs.
 * Os asserts sao identicos aos do projeto original; apenas o bootstrap e os caminhos foram adaptados.
 * Adaptacoes: caminhos frontend/* -> raiz
 */
const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage();await page.setContent('<div id="notesEditor" contenteditable="true"></div>');await page.addScriptTag({content:fs.readFileSync('notes/editor.js','utf8')});const result=await page.evaluate(()=>{class App{};installNotesEditor(App);const app=new App();app.recordNotesHistory=()=>{};app.rememberNotesSelection=()=>{};const root=document.getElementById('notesEditor');root.innerHTML=['A','B','C'].map(t=>`<div class="notes-line" data-list="ol" data-check="true" data-checked="false" data-level="0"><div class="notes-line-text">${t}</div></div>`).join('');app.refreshNotesCollapseControls();const state=()=>[...root.children].map(r=>r.querySelector('.notes-line-text').textContent+':'+r.querySelector('.notes-line-marker').textContent);const toggle=t=>{const row=[...root.children].find(r=>r.querySelector('.notes-line-text').textContent===t);const check=row.querySelector('input');check.checked=!check.checked;app.updateNotesChecklistOrder(check);app.updateNotesChecklistOrder(check);return state();};return [toggle('A'),toggle('B'),toggle('A')];});assert.deepEqual(result,[['B:2.','C:3.','A:1.'],['C:3.','B:2.','A:1.'],['C:3.','A:1.','B:2.']]);console.log('OK: pilha de concluídos, desmarcação e evento duplicado');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
// 🧪 [FIM: TESTE - NOTES CHECKLIST NUMBERS]
