// 🧪 [INÍCIO: TESTE - NOTES INDENT CHILD]
/*
 * Portado automaticamente de produtividade-ferrramenta/tests/notes_indent_child.cjs por tools/portar-testes.cjs.
 * Os asserts sao identicos aos do projeto original; apenas o bootstrap e os caminhos foram adaptados.
 * Adaptacoes: caminhos frontend/* -> raiz
 */
const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage();await p.setContent('<div id="notesEditor" contenteditable="true"><div class="notes-line" data-level="0" data-check="true" data-collapsed="true"><div class="notes-line-text">Pai</div></div><div class="notes-line" data-level="1"><div class="notes-line-text">Filho existente</div></div><div class="notes-line" data-level="0" data-heading="1"><div class="notes-line-text"><br></div></div></div>');await p.addScriptTag({content:fs.readFileSync('notes/editor.js','utf8')});await p.evaluate(()=>{class App{};installNotesEditor(App);const app=new App();app.recordNotesHistory=()=>{};app.rememberNotesSelection=()=>{};app.restoreNotesSelection=()=>{};app.refreshNotesCollapseControls();const root=document.getElementById('notesEditor');root.focus();const r=document.createRange();r.setStart(root.lastElementChild.querySelector('.notes-line-text'),0);r.collapse(true);getSelection().removeAllRanges();getSelection().addRange(r);root.addEventListener('keydown',e=>app.handleNotesEditorShortcut(e));});await p.keyboard.press('Tab');await p.keyboard.type('Novo filho');const state=await p.evaluate(()=>{const root=document.getElementById('notesEditor');return [root.firstElementChild.dataset.collapsed,root.lastElementChild.dataset.level,root.lastElementChild.dataset.heading,root.lastElementChild.hidden,root.lastElementChild.textContent];});assert.deepEqual(state,['false','1','',false,'Novo filho']);console.log('OK: Tab abre o pai e permite digitar no filho sem título');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
// 🧪 [FIM: TESTE - NOTES INDENT CHILD]
