// 🧪 [INÍCIO: TESTE - NOTES TONE PICKER]
/*
 * Portado automaticamente de produtividade-ferrramenta/tests/notes_tone_picker.cjs por tools/portar-testes.cjs.
 * Os asserts sao identicos aos do projeto original; apenas o bootstrap e os caminhos foram adaptados.
 * Adaptacoes: caminhos frontend/* -> raiz
 */
const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage();await p.setContent('<div id="notesModal" style="position:relative;margin-left:300px;width:400px"><button data-notes-color="color" title="Cor">Cor</button><div id="notesEditor"><div class="notes-line"><div class="notes-line-text">Texto</div></div></div></div>');await p.addStyleTag({content:fs.readFileSync('notes/editor.css','utf8')});await p.addScriptTag({content:fs.readFileSync('notes/editor.js','utf8')});await p.evaluate(()=>{class App{};installNotesEditor(App);window.app=new App();app.rememberNotesSelection=()=>{};app.recordNotesHistory=()=>{};app.setupNotesColors();});await p.locator('[data-notes-color]').click();await p.getByRole('button',{name:'Adicionar cor personalizada'}).click();const popup=p.getByRole('dialog',{name:'Escolher tonalidade'});await popup.getByRole('textbox',{name:'Hexadecimal'}).fill('#123456');await popup.getByRole('button',{name:'Cancelar'}).click();assert.equal(await p.locator('.notes-line').getAttribute('data-note-colors'),null);await p.getByRole('button',{name:'Adicionar cor personalizada'}).click();await popup.getByRole('textbox',{name:'Hexadecimal'}).fill('#123456');await popup.getByRole('textbox',{name:'Hexadecimal'}).press('Tab');await popup.getByRole('button',{name:'OK',exact:true}).click();assert.equal(await p.locator('.notes-line').getAttribute('data-note-colors'),'#123456');assert.equal(await p.locator('.notes-line').getAttribute('data-note-accent'),null);console.log('OK: seletor de tonalidade, cancelar, confirmar e independência da cor padrão');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
// 🧪 [FIM: TESTE - NOTES TONE PICKER]
