/*
 * Portado automaticamente de produtividade-ferrramenta/tests/test_notes_editor_ui.cjs por tools/portar-testes.cjs.
 * Os asserts sao identicos aos do projeto original; apenas o bootstrap e os caminhos foram adaptados.
 * Adaptacoes: entrada focus/sports.js removida; caminhos frontend/* -> raiz; TestApp = NotesPWA; ensureNotesFocusPage -> no-op; setupAntiInspection tolerante; motor instalado no prototipo (como o init do app faz)
 */
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
 const page=await browser.newPage({viewport:{width:1280,height:960},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
 const html=read('index.html').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,'');
 await page.route('**/*',r=>r.request().resourceType()==='document'?r.fulfill({contentType:'text/html',body:html}):r.abort());
 await page.goto('http://notes.test');
 for(const f of ['styles.css','notes/editor.css'])await page.addStyleTag({content:read(f)});
 for(const f of ['notes/editor.js'])await page.addScriptTag({content:read(f)});
 const source=read('app.js');await page.addScriptTag({content:source.slice(0,source.indexOf("document.addEventListener('DOMContentLoaded'"))+'\nwindow.TestApp = NotesPWA;'});
 await page.evaluate(()=>{
  document.documentElement.dataset.theme="light";window.app=Object.create(TestApp.prototype);app.userId=1;app.projectsData=[{id:1,nome:'Teste',notas:''}];app.focusStagesData=[{id:2,foco_id:1,titulo:'Etapa',notas:''}];app.ensureNotesFocusPage = () => {};app.showToast=()=>{};if (!TestApp.prototype.__motorInstalado) { installNotesEditor(TestApp); if (typeof installNotesExtras === 'function') installNotesExtras(TestApp); if (typeof installNotesTables === 'function') installNotesTables(TestApp); if (typeof installLocalNotesStorage === 'function') installLocalNotesStorage(TestApp); TestApp.prototype.__motorInstalado = true; } if (app.setupEventListeners) app.setupEventListeners(); app.setupModalListeners();if (app.setupAntiInspection) app.setupAntiInspection();
  window.calls=[];app.apiCall=async(url,options)=>{calls.push({url,...JSON.parse(options.body)});return{};};
  window.loadNote=async html=>{clearTimeout(app.notesSaveTimer);app.notesSession=null;app.projectsData[0].notas=html;localStorage.clear();await app.openNotesModal(1);};
  window.selectText=(a,start,b=a,end=start)=>{document.getElementById('notesEditor').focus();const rows=[...document.querySelectorAll('#notesEditor .notes-line-text')];function point(row,n){const w=document.createTreeWalker(row,NodeFilter.SHOW_TEXT);let t=w.nextNode();while(t&&n>t.length){n-=t.length;t=w.nextNode();}return t?[t,n]:[row,0];}const r=document.createRange();r.setStart(...point(rows[a],start));r.setEnd(...point(rows[b],end));getSelection().removeAllRanges();getSelection().addRange(r);app.rememberNotesSelection();};
 });
 const load=async html=>{await page.evaluate(html=>loadNote(html),html);await page.waitForTimeout(400);await page.locator('#notesEditor').click();};
 const select=async(a,s,b=a,e=s)=>page.evaluate(args=>selectText(...args),[a,s,b,e]);
 const command=async c=>page.evaluate(c=>app.executeNotesCommand(c),c);
 const rows=()=>page.locator('#notesEditor .notes-line');
 const text=()=>page.locator('#notesEditor .notes-line-text').allTextContents();
 await load('<ol><li>Primeiro</li><li>Segundo</li></ol>');await select(0,0,1,7);await command('checklist');
 assert.deepEqual(await text(),['Primeiro','Segundo']);assert.equal(await page.locator('.notes-line-check').count(),2);
 assert.deepEqual(await page.locator('.notes-line-marker').allTextContents(),['1.','2.']);
 await select(1,7);await page.keyboard.press('Enter');await page.keyboard.type('Terceiro');assert.deepEqual(await text(),['Primeiro','Segundo','Terceiro']);
 assert.equal(await page.locator('.notes-line-check').count(),3);
 await select(0,0);await page.keyboard.press('Enter');assert.deepEqual(await text(),['','Primeiro','Segundo','Terceiro']);
 await select(1,0);await page.keyboard.press('Backspace');assert.equal(await rows().nth(1).getAttribute('data-list'),'');assert.equal(await rows().nth(1).getAttribute('data-check'),'true');
 await page.keyboard.press('Backspace');assert.equal(await rows().nth(1).getAttribute('data-check'),'false');
 await load('<div class="checklist-item"><input type="checkbox"><span class="checklist-text">Tarefa</span></div>');await select(0,2);await command('insertOrderedList');assert.equal(await page.locator('.notes-line-check').count(),1);assert.equal(await page.locator('.notes-line-marker').textContent(),'1.');
 await load('<ol><li>Um</li></ol><p>Dois</p><ol><li>Três</li></ol>');await select(1,2);await command('insertOrderedList');assert.deepEqual(await page.locator('.notes-line-marker').allTextContents(),['1.','2.','3.']);
 await select(1,0,2,4);await page.keyboard.press('Tab');assert.deepEqual(await rows().evaluateAll(rows=>rows.map(r=>r.dataset.level)),['0','1','1']);
 await page.keyboard.press('Shift+Tab');assert.deepEqual(await rows().evaluateAll(rows=>rows.map(r=>r.dataset.level)),['0','0','0']);
 await select(1,1);await command('moveUp');assert.deepEqual(await text(),['Dois','Um','Três']);await command('undo');assert.deepEqual(await text(),['Um','Dois','Três']);await command('redo');assert.deepEqual(await text(),['Dois','Um','Três']);
 await select(0,1);await command('heading1');await command('heading2');assert.equal(await rows().nth(0).getAttribute('data-heading'),'2');assert.equal(await rows().count(),3);assert.equal(await rows().nth(0).getAttribute('data-level'),'0');await command('heading2');assert.equal(await rows().nth(0).getAttribute('data-heading'),'');
 await load('<ol><li>Pai<ol><li>Filho</li></ol></li><li>Irmão</li></ol>');await select(0,3);await page.keyboard.press('Enter');assert.deepEqual(await rows().evaluateAll(rows=>rows.map(r=>r.dataset.level)),['0','1','1','0']);
 await page.keyboard.type('Novo filho');await select(0,0,0,3);await command('bold');assert.equal(await page.locator('.notes-line-collapse').count(),1);
 const before=await page.evaluate(()=>getSelection().toString());await page.locator('.notes-line-collapse').click();await page.waitForTimeout(250);assert.equal(await rows().nth(1).isVisible(),false);await page.locator('.notes-line-collapse').click();await page.waitForTimeout(250);assert.equal(await rows().nth(1).isVisible(),true);assert.equal(await page.evaluate(()=>getSelection().toString()),before);
 await select(1,2);await page.keyboard.press('Shift+Enter');assert.equal(await rows().count(),4);
 await page.evaluate(()=>app.toggleNotesFullscreen());assert.equal(await page.locator('#notesToolbar').isVisible(),false);await page.evaluate(()=>app.toggleNotesHeaderCollapse());assert.equal(await page.locator('#notesToolbar').isVisible(),true);
 assert.equal(await page.evaluate(()=>{const e=new MouseEvent('contextmenu',{bubbles:true,cancelable:true});document.querySelector('.notes-line-text').dispatchEvent(e);return e.defaultPrevented;}),false);
 await load('<p>Salvar</p>');await select(0,6);await page.keyboard.type(' automaticamente');await page.waitForTimeout(1250);assert.ok(await page.evaluate(()=>calls.at(-1).notas.includes('automaticamente')));
 await page.evaluate(()=>{window.release=null;app.apiCall=async(url,o)=>{calls.push({url,...JSON.parse(o.body)});await new Promise(r=>release=r);};});
 await select(0,0);await page.keyboard.type('A');await page.evaluate(()=>{app.saveNotes();});await page.waitForFunction(()=>release);await page.keyboard.type('B');await page.evaluate(()=>{const r=release;app.apiCall=async(url,o)=>calls.push({url,...JSON.parse(o.body)});r();});await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>calls.at(-1).notas.includes('ABSalvar')));
 await page.evaluate(()=>{app.apiCall=async()=>{throw Error('offline');};});await page.keyboard.type('C');assert.equal(await page.evaluate(()=>app.closeNotesModal()),false);assert.equal(await page.locator('#notesModalBackdrop').evaluate(e=>e.classList.contains('active')),true);assert.ok((await page.locator('#notesSaveStatus').textContent()).includes('Falha'));
 await page.evaluate(()=>{app.apiCall=async(url,o)=>calls.push({url,...JSON.parse(o.body)});});assert.equal(await page.evaluate(()=>app.closeNotesModal()),true);
 await page.evaluate(()=>{localStorage.setItem('notes-draft:1:1:focus',JSON.stringify({html:'<p>Recuperado</p>'}));app.openNotesModal(1);});await page.getByRole('button',{name:'Recuperar rascunho'}).click();assert.deepEqual(await text(),['Recuperado']);await page.evaluate(()=>app.saveNotes());
 await load('<ol><li>Um</li><li>Dois</li><li>Três</li></ol>');await select(0,1,1,2);await page.keyboard.press('Backspace');assert.deepEqual(await text(),['Uis','Três']);assert.deepEqual(await page.locator('.notes-line-marker').allTextContents(),['1.','2.']);
 await load('<ol><li>Um</li><li>Dois</li><li>Três</li></ol>');await select(0,0,2,4);await page.keyboard.press('Backspace');assert.equal(await rows().count(),1);await page.keyboard.type('Recomeçar');assert.deepEqual(await text(),['Recomeçar']);
 await load('<div class="checklist-item" data-indent-level="1"><input type="checkbox" checked><span class="checklist-text"><strong>Destino</strong></span></div>');await select(0,7);
 await page.evaluate(()=>{const data=new DataTransfer();data.setData('text/plain',' colado\noutra linha');document.getElementById('notesEditor').dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:data}));});
 assert.equal(await rows().count(),1);assert.equal(await rows().nth(0).getAttribute('data-level'),'1');assert.ok((await text())[0].includes('Destino colado'));assert.equal(await page.locator('.notes-line-check').isChecked(),true);
 await select(0,0);await page.evaluate(()=>{const data=new DataTransfer();data.setData('text/html','<b>Negrito</b>');data.setData('text/plain','Negrito');document.getElementById('notesEditor').dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:data}));});assert.equal(await page.locator('.notes-line-text b').textContent(),'Negrito');
 await load('<ol><li>Pai<ol><li>Filho</li></ol></li><li>Outro</li></ol>');await select(0,0,1,5);
 await page.evaluate(()=>{const data=new DataTransfer();document.getElementById('notesEditor').dispatchEvent(new ClipboardEvent('copy',{bubbles:true,cancelable:true,clipboardData:data}));window.copiedNotes=data.getData('application/x-productivity-notes');});assert.ok(await page.evaluate(()=>copiedNotes.includes('data-level="1"')));
 await select(2,5);await page.evaluate(()=>{const data=new DataTransfer();data.setData('application/x-productivity-notes',copiedNotes);document.getElementById('notesEditor').dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:data}));});assert.deepEqual(await text(),['Pai','Filho','Outro','Pai','Filho']);assert.deepEqual(await rows().evaluateAll(rs=>rs.map(r=>r.dataset.level)),['0','1','0','0','1']);
 await select(0,2);await command('moveDown');assert.deepEqual(await text(),['Outro','Pai','Filho','Pai','Filho']);
 await load('<p>Palavra longa para verificar o título e o alinhamento dos marcadores</p><p>Detalhe</p>');await select(0,2);
 await page.locator('[data-command=heading1]').click();assert.equal(await rows().nth(0).getAttribute('data-heading'),'1');await page.locator('[data-command=heading1]').click();assert.equal(await rows().nth(0).getAttribute('data-heading'),'');
 await page.locator('[data-command=heading2]').click();assert.equal(await rows().nth(0).getAttribute('data-heading'),'2');await command('checklist');await command('insertOrderedList');
 assert.deepEqual(await rows().nth(0).locator('.notes-line-controls').evaluate(e=>[...e.children].filter(e=>e.tagName!=='BUTTON').map(e=>e.tagName)),['INPUT','SPAN']);
 await select(1,0);await page.keyboard.press('Tab');await page.locator('.notes-line-check').click();assert.equal(await rows().nth(0).getAttribute('data-checked'),'true');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('#notesModal').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);
 const out=path.join(__dirname,'..','.states','notes-qa');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'mobile.png')});
 await page.locator('.notes-line-collapse').click();await page.waitForTimeout(250);const position=await page.locator('.notes-line-check').boundingBox();await page.locator('.notes-line-collapse').click();await page.waitForTimeout(250);assert.deepEqual(await page.locator('.notes-line-check').boundingBox(),position);
 await page.setViewportSize({width:1280,height:960});await page.screenshot({path:path.join(out,'desktop.png')});
 await page.locator('#notesModalClose').click();await page.waitForFunction(()=>!app.currentNotesProjectId);assert.ok(await page.evaluate(()=>calls.at(-1).notas.includes('Palavra longa')));
 await page.evaluate(()=>app.openStageNotesModal(2));await page.waitForTimeout(400);await page.locator('#notesEditor').click();await select(0,0);await page.keyboard.type('Etapa salva');await page.evaluate(()=>app.closeNotesModal());assert.equal(await page.evaluate(()=>calls.at(-1).url),'/focus-stages/2');
 await load('<p>Fora</p>');await select(0,4);await page.keyboard.type(' salvo');await page.locator('#notesModalBackdrop').click({position:{x:1200,y:500}});await page.waitForFunction(()=>!app.currentNotesProjectId);assert.ok(await page.evaluate(()=>calls.at(-1).notas.includes('Fora salvo')));
 await load('<p>Escape</p>');await select(0,6);await page.keyboard.type(' salvo');await page.keyboard.press('Escape');await page.waitForFunction(()=>!app.currentNotesProjectId);assert.ok(await page.evaluate(()=>calls.at(-1).notas.includes('Escape salvo')));
 await load('<strong>Antigo</strong> com <em>formatação</em>');assert.deepEqual(await text(),['Antigo com formatação']);assert.equal(await page.locator('.notes-line-text strong').textContent(),'Antigo');
 await page.evaluate(()=>app.saveNotes());await page.evaluate(()=>app.closeNotesModal());
 await load('<p><br></p>');await select(0,0);await page.keyboard.type('1. Item');assert.equal(await rows().nth(0).getAttribute('data-list'),'ol');assert.deepEqual(await text(),['Item']);
 await page.evaluate(()=>app.closeNotesModal());
 await load('<p><br></p>');await select(0,0);await page.keyboard.press('Enter');await page.keyboard.press('Enter');assert.equal(await rows().count(),2);assert.equal(await rows().nth(1).getAttribute('data-heading'),'');await page.keyboard.type('Linha vazia funciona');assert.deepEqual(await text(),['','Linha vazia funciona']);
 await load('<div class="checklist-item"><input type="checkbox"><span class="checklist-text"></span></div><p>Texto abaixo</p>');await select(1,0);await page.keyboard.press('Backspace');assert.deepEqual(await text(),['Texto abaixo']);assert.equal(await page.locator('.notes-line-check').count(),1);
 await page.locator('.notes-line-check').focus();await page.keyboard.press('Space');assert.equal(await rows().nth(0).getAttribute('data-checked'),'true');await page.keyboard.press('Space');assert.equal(await rows().nth(0).getAttribute('data-checked'),'false');
 const touchBox=await page.locator('.notes-line-check').boundingBox();await page.touchscreen.tap(touchBox.x+7,touchBox.y+7);assert.equal(await rows().nth(0).getAttribute('data-checked'),'true');await page.touchscreen.tap(touchBox.x+7,touchBox.y+7);assert.equal(await rows().nth(0).getAttribute('data-checked'),'false');
 await page.evaluate(()=>app.saveNotes());await page.evaluate(()=>app.closeNotesModal());await page.evaluate(()=>app.openNotesModal(1));await page.locator('.notes-line-check').waitFor({state:'visible'});assert.equal(await page.locator('.notes-line-check').isChecked(),false);
 await page.evaluate(()=>{window.motion=app.toggleNotesFullscreen();});await page.waitForTimeout(320);assert.equal(await page.locator('#notesToolbar').isVisible(),true);assert.equal(await page.locator('#notesContextNav').isVisible(),true);await page.evaluate(()=>motion);assert.equal(await page.locator('#notesToolbar').isVisible(),false);assert.equal(await page.locator('#notesContextNav').isVisible(),false);
 assert.deepEqual(await page.evaluate(async()=>{window.motion=app.toggleNotesFullscreen();await new Promise(resolve=>setTimeout(resolve,150));return [document.getElementById('notesToolbar').hidden,document.getElementById('notesContextNav').hidden];}),[true,true]);await page.evaluate(()=>motion);assert.equal(await page.locator('#notesToolbar').isVisible(),true);assert.equal(await page.locator('#notesContextNav').isVisible(),true);
 await page.evaluate(async()=>{const a=app.toggleNotesFullscreen();const b=app.toggleNotesFullscreen();await Promise.all([a,b]);});assert.equal(await page.locator('#notesToolbar').isVisible(),true);
 const handle=page.locator('#notesResizeHandle');assert.equal(await handle.evaluate(e=>e.getBoundingClientRect().width),5);await handle.focus();await page.keyboard.press('Home');await page.waitForTimeout(350);assert.ok(Math.abs((await page.locator('#notesModal').boundingBox()).width-360)<2);
 await page.keyboard.press('ArrowRight');await page.waitForTimeout(350);assert.ok(Math.abs((await page.locator('#notesModal').boundingBox()).width-384)<2);
 const box=await handle.boundingBox();await page.mouse.move(box.x+2,400);await page.mouse.down();await page.mouse.move(1275,400,{steps:8});await page.mouse.up();await page.waitForTimeout(1000);assert.equal(await page.locator('#notesModal').evaluate(e=>e.classList.contains('fullscreen')),true);await page.evaluate(()=>app.toggleNotesFullscreen());assert.ok(Math.abs((await page.locator('#notesModal').boundingBox()).width-384)<2);
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>app.toggleNotesFullscreen());assert.equal(await page.locator('#notesToolbar').isVisible(),false);await page.evaluate(()=>app.toggleNotesFullscreen());
 assert.equal(await page.locator('#notesEditor').getAttribute('lang'),'pt-BR');assert.equal(await page.locator('#notesEditor').evaluate(e=>e.spellcheck),true);
 await page.evaluate(()=>app.closeNotesModal());
 await load('<ol><li>Anterior</li><li class="note-heading note-heading-1">Selecionado<ol><li>Filho</li></ol></li><li>Mesmo nível</li></ol>');await select(1,2);await command('indent');
 assert.deepEqual(await rows().evaluateAll(rs=>rs.map(r=>r.dataset.level)),['0','1','2','0']);
 const childWasVisible=await rows().nth(2).isVisible();await rows().nth(1).locator('.notes-line-collapse').click();await page.waitForTimeout(250);assert.equal(await rows().nth(2).isVisible(),!childWasVisible);assert.equal(await rows().nth(3).isVisible(),true);await rows().nth(1).locator('.notes-line-collapse').click();await page.waitForTimeout(250);assert.equal(await rows().nth(2).isVisible(),childWasVisible);
 const arrow=await rows().nth(1).locator('.notes-line-collapse svg').boundingBox();const button=await rows().nth(1).locator('.notes-line-collapse').boundingBox();assert.ok(arrow.y>=button.y&&arrow.y+arrow.height<=button.y+button.height);
 await page.evaluate(()=>app.closeNotesModal());
 await load('<h1>Primeira segunda</h1>');await select(0,0);await page.keyboard.press('Enter');assert.equal(await rows().nth(1).getAttribute('data-heading'),'1');assert.deepEqual(await text(),['','Primeira segunda']);
 await select(1,0,1,8);await command('heading1');assert.equal(await rows().nth(1).getAttribute('data-heading'),'1');assert.equal(await rows().nth(1).locator('[data-inline-heading="0"]').textContent(),'Primeira');
 await command('heading2');assert.equal(await rows().nth(1).locator('[data-inline-heading="2"]').textContent(),'Primeira');assert.ok((await rows().nth(1).locator('.notes-line-text').textContent()).includes('segunda'));
 await select(1,3);await command('heading3');assert.equal(await rows().nth(1).getAttribute('data-heading'),'3');assert.equal(await rows().nth(1).locator('[data-inline-heading]').count(),0);
 await command('insertOrderedList');await command('bold');await command('italic');assert.equal(await rows().nth(1).locator('.notes-line-marker').evaluate(e=>getComputedStyle(e).fontWeight),'700');assert.equal(await rows().nth(1).locator('.notes-line-marker').evaluate(e=>getComputedStyle(e).fontStyle),'italic');
 await select(1,0,1,8);await page.evaluate(()=>{const data=new DataTransfer();document.getElementById('notesEditor').dispatchEvent(new ClipboardEvent('copy',{bubbles:true,cancelable:true,clipboardData:data}));window.exportedCopy=data.getData('text/html');});assert.ok(!(await page.evaluate(()=>exportedCopy)).includes('background'));
 await load('<p><br></p>');await select(0,0);await page.keyboard.press('Enter');assert.equal(await rows().nth(1).getAttribute('data-heading'),'1');
 await page.evaluate(()=>app.closeNotesModal());
 await load('<ol><li>Pai<ol><li>Selecionado<ol><li>Filho</li></ol></li><li>Irmão</li></ol></li></ol>');await select(1,3);await command('outdent');assert.deepEqual(await text(),['Pai','Irmão','Selecionado','Filho']);assert.deepEqual(await rows().evaluateAll(rs=>rs.map(r=>r.dataset.level)),['0','1','0','1']);await command('indent');assert.deepEqual(await rows().evaluateAll(rs=>rs.map(r=>r.dataset.level)),['0','1','1','2']);assert.equal(await page.evaluate(()=>getSelection().anchorNode.parentElement.closest('.notes-line').querySelector('.notes-line-text').textContent),'Selecionado');
 await page.evaluate(()=>app.closeNotesModal());
 await load('<ol><li>Pai<ol><li>Filho</li></ol></li></ol>');await select(0,1);await command('checklist');
 const gaps=await rows().nth(0).evaluate(r=>{const collapse=r.querySelector('.notes-line-collapse').getBoundingClientRect(),check=r.querySelector('.notes-line-check').getBoundingClientRect(),marker=r.querySelector('.notes-line-marker').getBoundingClientRect(),text=r.querySelector('.notes-line-text').getBoundingClientRect();return [check.left-collapse.right,marker.left-check.right,text.left-marker.right,Math.abs((check.top+check.bottom)/2-(collapse.top+collapse.bottom)/2)];});assert.ok(gaps.every((g,i)=>Math.abs(g-[4,4,6,0][i])<1));
 await page.evaluate(()=>app.closeNotesModal());
 await load('<ol><li><strong>Negrito</strong></li><li><em>Itálico</em></li></ol><ul><li><strong><em>Ambos</em></strong></li></ul>');
 const markerStyles=()=>rows().evaluateAll(rs=>rs.map(r=>{const s=getComputedStyle(r.querySelector('.notes-line-marker'));return [s.fontWeight,s.fontStyle];}));
 assert.deepEqual(await markerStyles(),[['700','normal'],['400','italic'],['700','italic']]);
 await page.evaluate(()=>app.closeNotesModal());await load('<ol><li>Primeira segunda</li></ol>');
 await select(0,0,0,8);await command('bold');assert.deepEqual(await markerStyles(),[['400','normal']]);
 await select(0,0,0,16);await command('bold');assert.deepEqual(await markerStyles(),[['700','normal']]);
 await command('italic');assert.deepEqual(await markerStyles(),[['700','italic']]);
 await page.evaluate(()=>app.closeNotesModal());await page.evaluate(()=>app.openNotesModal(1));assert.deepEqual(await markerStyles(),[['700','italic']]);
 for(const width of [1280,390]){
  await page.setViewportSize({width,height:960});await select(0,0);
  await page.locator('[data-notes-color="color"]').click();
  const palette=page.locator('#notesColorPalette');await palette.waitFor({state:'visible'});
  assert.equal(await palette.locator('.notes-color-grid button').count(),80);
  const box=await palette.boundingBox();assert.ok(box.width<=244&&box.x>=0&&box.x+box.width<=width);
  assert.equal(await palette.evaluate(e=>getComputedStyle(e).position),'fixed');
  const swatch=await palette.locator('.notes-color-grid button').first().boundingBox();assert.ok(swatch.width>=20&&swatch.height>=20);
  await palette.getByRole('button',{name:'#ff0000',exact:true}).click();assert.equal(await palette.count(),0);
 }
 assert.deepEqual(errors,[]);console.log('OK: edição, checkbox, linhas vazias, autosave, expansão sequencial, resize e redução de movimento.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
