/* Optional note tools; no file viewers are loaded during typing. */
function installNotesExtras(App){
 const p=App.prototype,setup=p.setupNotesEditing,clean=p.getCleanNotesHtml,refresh=p.refreshNotesCollapseControls;
 const editor=()=>document.getElementById('notesEditor'),body=row=>row?.querySelector(':scope > .notes-line-text');
 const rowAt=node=>(node?.nodeType===3?node.parentElement:node)?.closest?.('.notes-line');
 const safeURL=value=>{try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.href:null;}catch{return null;}};
 const youtube=value=>{try{const url=new URL(value);if(url.hostname==='youtu.be')return url.pathname.slice(1).match(/^[\w-]{11}$/)?.[0];if(/^(www\.|m\.)?youtube\.com$/.test(url.hostname))return (url.searchParams.get('v')||url.pathname.split('/').at(-1)).match(/^[\w-]{11}$/)?.[0];}catch{}return null;};
 const button=(label,text,action)=>{const el=document.createElement('button');el.type='button';el.textContent=text;el.title=label;el.setAttribute('aria-label',label);el.onmousedown=e=>e.preventDefault();el.onclick=action;return el;};
 p.notesExtraRequest=async function(path,options={}){const response=await fetch('/api/note-assets'+path+(path.includes('?')?'&':'?')+'user_id='+this.userId,options);if(!response.ok){const error=await response.json().catch(()=>({}));throw Error(error.detail||'Não foi possível concluir a operação');}return response.json();};
 // Keep a private range for the whole interaction, including native file pickers.
 p.notesCaptureInsertion=function(){this.rememberNotesSelection();return {range:this.notesSelectionRange?.cloneRange(),session:this.notesSession};};
 p.notesRestoreInsertion=function(saved){if(saved?.session!==this.notesSession)return false;if(saved?.range&&editor().contains(saved.range.commonAncestorContainer))this.notesSelectionRange=saved.range.cloneRange();this.restoreNotesSelection();return true;};
 p.notesExtraDialog=function(title,build,trigger){
  const saved=this.notesCaptureInsertion(),tool=title==='Editar link'?'link':title==='Modelos de nota'?'templates':'insert';let anchor=trigger||document.querySelector('#notesToolbar [data-extra="'+tool+'"]')||document.getElementById('notesToolbar');if(!anchor.getClientRects().length)anchor=document.querySelector('.notes-toolbar-more')||document.getElementById('notesToolbar');
  const dialog=document.createElement('dialog');dialog.className='notes-extra-dialog';const heading=document.createElement('h3');heading.textContent=title;const close=button('Fechar','×',()=>dialog.close());close.className='notes-extra-close';dialog.append(heading,close);document.body.append(dialog);
  const nativeClose=dialog.close.bind(dialog);dialog.close=()=>{nativeClose();dialog.remove();this.notesRestoreInsertion(saved);};
  dialog.addEventListener('cancel',e=>{e.preventDefault();dialog.close();});dialog.addEventListener('keydown',e=>{if(e.key==='Escape')e.stopPropagation();});
  dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close();});
  const position=()=>{const r=anchor.getBoundingClientRect(),w=dialog.offsetWidth,h=dialog.offsetHeight;dialog.style.left=Math.max(12,Math.min(innerWidth-w-12,r.right-w))+'px';dialog.style.top=Math.max(12,Math.min(innerHeight-h-12,r.bottom+8))+'px';};
  build(dialog);dialog.showModal();position();const observer=new ResizeObserver(position);observer.observe(dialog);window.addEventListener('resize',position);dialog.addEventListener('close',()=>{observer.disconnect();window.removeEventListener('resize',position);dialog.remove();});return dialog;
 };
 p.notesRevealInsertion=function(row){
  // Inserting the first child must not trigger the default collapsed state.
  const stack=[];for(const current of editor().children){while(stack.length){const parent=stack.at(-1);if(current.dataset.outlineBreak&&parent.dataset.heading&&Number(current.dataset.outlineBreak)<=Number(parent.dataset.heading)&&Number(current.dataset.level||0)<=Number(parent.dataset.level||0)){stack.pop();continue;}if(Number(current.dataset.level||0)>Number(parent.dataset.level||0)||!parent.dataset.list&&parent.dataset.check!=='true'&&parent.dataset.heading&&(!current.dataset.heading||Number(current.dataset.heading)>Number(parent.dataset.heading)))break;stack.pop();}stack.push(current);if(current===row)break;}for(const parent of stack)parent.dataset.collapsed='false';
 };
 p.notesInsertNode=function(node){
  this.flushNotesTyping();this.restoreNotesSelection();const selection=getSelection();let range=selection.rangeCount?selection.getRangeAt(0):null;
  if(!range||!editor().contains(range.commonAncestorContainer)||!rowAt(range.startContainer)){let target=body(editor().lastElementChild);if(!target){const row=document.createElement('div');row.className='notes-line';target=document.createElement('div');target.className='notes-line-text';row.append(target);editor().append(row);}range=document.createRange();range.selectNodeContents(target);range.collapse(false);}
  range.deleteContents();const active=rowAt(range.startContainer);if(active)this.notesRevealInsertion(active);
  if(node.matches?.('figure,table')){
   const current=rowAt(range.startContainer),text=body(current);if(current&&text){const tail=document.createRange();tail.selectNodeContents(text);tail.setStart(range.startContainer,range.startOffset);const suffix=tail.extractContents(),row=document.createElement('div');row.className='notes-line';row.dataset.level=current.dataset.level||'0';for(const key of ['noteAccent','noteColors','noteHighlightColors','noteAccentHistory'])if(current.dataset[key])row.dataset[key]=current.dataset[key];const content=document.createElement('div');content.className='notes-line-text';content.append(node);row.append(content);current.after(row);if(suffix.textContent.trim()||suffix.querySelector('img,figure')){const next=row.cloneNode(false),body=document.createElement('div');body.className='notes-line-text';body.append(suffix);next.append(body);row.after(next);}if(!text.textContent.trim()&&!text.querySelector('img,table,figure'))current.remove();this.recordNotesHistory();range=document.createRange();range.selectNodeContents(node.matches('table')?node.rows[0].cells[0]:content);range.collapse(node.matches('table'));editor().focus({preventScroll:true});selection.removeAllRanges();selection.addRange(range);node.scrollIntoView({block:'nearest',inline:'nearest'});this.rememberNotesSelection();return;}
  }
  range.insertNode(node);rowAt(node)?.querySelectorAll('a:empty').forEach(link=>link.remove());range.setStartAfter(node);range.collapse(true);selection.removeAllRanges();selection.addRange(range);this.recordNotesHistory();this.rememberNotesSelection();
 };
 p.notesDivider=function(){
  this.flushNotesTyping();this.restoreNotesSelection();const row=rowAt(getSelection().anchorNode);if(!row)return;const text=body(row),divider=text.querySelector('hr');
  if(divider){divider.remove();if(!text.textContent)text.replaceChildren(document.createElement('br'));}
  else {if(text.textContent.trim()||text.querySelector('img,table,figure,a')){this.showToast('Posicione o cursor em uma linha vazia.');return;}const hr=document.createElement('hr');hr.contentEditable='false';text.replaceChildren(hr);}
  const range=document.createRange();range.selectNodeContents(text);range.collapse(false);getSelection().removeAllRanges();getSelection().addRange(range);this.recordNotesHistory();this.rememberNotesSelection();
 };
 p.notesLinkDialog=function(){
  this.rememberNotesSelection();const selection=getSelection(),selected=selection.toString(),anchor=(selection.anchorNode?.nodeType===3?selection.anchorNode.parentElement:selection.anchorNode)?.closest?.('a')||[...(rowAt(selection.anchorNode)?.querySelectorAll('a')||[])].find(link=>selected===link.textContent&&selection.rangeCount&&selection.getRangeAt(0).intersectsNode(link));
  this.notesExtraDialog('Editar link',dialog=>{const form=document.createElement('form');const title=document.createElement('input'),url=document.createElement('input');title.value=anchor?(anchor.textContent===anchor.href?'':anchor.textContent):safeURL(selected)?'':selected;url.value=anchor?.href||safeURL(selected)||'';url.type='url';url.required=true;
   for(const [label,input]of [['Título',title],['Link',url]]){const el=document.createElement('label');el.textContent=label;el.append(input);form.append(el);}const ok=button('Confirmar link','OK');ok.type='submit';form.append(ok);form.onsubmit=e=>{e.preventDefault();const href=safeURL(url.value);if(!href)return;dialog.close();if(anchor?.isConnected){anchor.href=href;anchor.textContent=title.value.trim()||href;this.recordNotesHistory();}else{const link=document.createElement('a');link.href=href;link.target='_blank';link.rel='noopener noreferrer';link.textContent=title.value.trim()||href;this.notesInsertNode(link);}};dialog.append(form);
  });
 };
 p.notesAutoLinks=function(row,commit=true){
  if(!row?.isConnected||row.dataset.codeBlock||row.classList.contains('notes-code-line'))return;
  const selection=getSelection(),saved=selection.rangeCount?selection.getRangeAt(0).cloneRange():null,offsets=saved&&body(row).contains(saved.commonAncestorContainer)?(()=>{const r=document.createRange();r.selectNodeContents(body(row));r.setEnd(saved.startContainer,saved.startOffset);const start=r.toString().length;r.setEnd(saved.endContainer,saved.endOffset);return [start,r.toString().length];})():null,walker=document.createTreeWalker(body(row),NodeFilter.SHOW_TEXT),nodes=[];
  while(walker.nextNode())if(!walker.currentNode.parentElement.closest('a,code,pre,figure'))nodes.push(walker.currentNode);
  let changed=false;for(const node of nodes){const matches=[...node.data.matchAll(/https?:\/\/[^\s<>]+/g)];if(!matches.length)continue;const fragment=document.createDocumentFragment();let offset=0;for(const match of matches){const value=match[0].replace(/[.,;!?]+$/,'');if(!safeURL(value))continue;fragment.append(document.createTextNode(node.data.slice(offset,match.index)));const link=document.createElement('a');link.href=value;link.textContent=value;link.target='_blank';link.rel='noopener noreferrer';fragment.append(link);offset=match.index+value.length;}fragment.append(document.createTextNode(node.data.slice(offset)));node.replaceWith(fragment);changed=true;}
  if(changed){if(commit)this.recordNotesHistory();if(offsets){const point=n=>{const w=document.createTreeWalker(body(row),NodeFilter.SHOW_TEXT);let last;while(w.nextNode()){last=w.currentNode;if(n<=last.length)return [last,n];n-=last.length;}return last?[last,last.length]:[body(row),0];};const r=document.createRange();r.setStart(...point(offsets[0]));r.setEnd(...point(offsets[1]));selection.removeAllRanges();selection.addRange(r);this.rememberNotesSelection();}else if(saved&&editor().contains(saved.startContainer)){selection.removeAllRanges();selection.addRange(saved);}}return changed;
 };
 p.notesFocusMedia=function(media){
  media.tabIndex=0;const range=document.createRange();range.setStartAfter(media);range.collapse(true);getSelection().removeAllRanges();getSelection().addRange(range);media.focus({preventScroll:true});this.rememberNotesSelection();
 };
 p.notesBackspaceMedia=function(){
  const selection=getSelection();if(!selection.isCollapsed)return false;
  let media=document.activeElement?.closest?.('.notes-media');
  if(!media&&selection.rangeCount){const range=selection.getRangeAt(0);if(range.startContainer.nodeType===1)media=range.startContainer.childNodes[range.startOffset-1];}
  if(!media?.matches?.('.notes-media,a[data-note-asset]')||!editor().contains(media))return false;
  this.flushNotesTyping();const text=body(rowAt(media)),range=document.createRange();range.setStartBefore(media);range.collapse(true);media.remove();if(!text.childNodes.length)text.append(document.createElement('br'));editor().focus({preventScroll:true});getSelection().removeAllRanges();getSelection().addRange(range);this.recordNotesHistory();this.rememberNotesSelection();return true;
 };
 p.notesMedia=function(kind,value,name){
  const figure=document.createElement('figure');figure.className='notes-media';figure.contentEditable='false';figure.tabIndex=0;figure.title='Clique para posicionar o cursor. Backspace remove este item.';figure.style.width='min(480px, 100%)';figure.style.maxWidth='100%';
  if(kind==='image'){const img=document.createElement('img');img.src=value;img.alt=name||'Imagem';img.loading='lazy';figure.append(img);}else{figure.dataset.youtube=value;const poster=document.createElement('img');poster.src='https://i.ytimg.com/vi/'+value+'/hqdefault.jpg';poster.alt='Prévia do vídeo do YouTube';poster.loading='lazy';poster.dataset.videoPoster='true';const play=button('Reproduzir vídeo','▶ Reproduzir vídeo do YouTube');play.className='notes-video-play';figure.append(poster,play);}
  const controls=document.createElement('span');controls.className='notes-media-controls';for(const [label,action]of [['↑','up'],['↓','down'],['−','smaller'],['+','larger']]){const b=button(action==='up'?'Mover para cima':action==='down'?'Mover para baixo':action==='smaller'?'Diminuir':'Aumentar',label);b.dataset.mediaAction=action;controls.append(b);}figure.append(controls);this.notesInsertNode(figure);
 };
 p.notesVideoDialog=function(initial=''){this.notesExtraDialog('Incorporar vídeo do YouTube',dialog=>{const input=document.createElement('input');input.type='url';input.placeholder='Link do YouTube';input.value=initial;dialog.append(input,button('Incorporar','Incorporar',()=>{const id=youtube(input.value);if(!id){input.setCustomValidity('Informe um link válido do YouTube');input.reportValidity();return;}dialog.close();this.notesMedia('video',id);}));});};
 p.notesUpload=function(image=false){
  const saved=this.notesCaptureInsertion();const input=document.createElement('input');input.type='file';input.accept=image?'.png,.jpg,.jpeg,.webp,.gif,.bmp,.avif,.tif,.tiff':'.pdf,.docx,.xlsx,.csv';
  input.onchange=async()=>{const file=input.files[0];if(!file)return;try{this.notesStatus('Enviando arquivo…');const data=new FormData();data.append('file',file);const asset=await this.notesExtraRequest('/files',{method:'POST',body:data});if(!this.notesRestoreInsertion(saved))return;const url='/api/note-assets/files/'+asset.id+'?user_id='+this.userId;if(image)this.notesMedia('image',url,asset.name);else{const link=document.createElement('a');link.href=url;link.dataset.noteAsset=asset.id;link.textContent='📎 '+asset.name;this.notesInsertNode(link);}}catch(error){this.showToast(error.message,'error');}};input.click();
 };
 p.notesInsertMenu=function(){
  this.notesExtraDialog('Inserir',dialog=>{dialog.classList.add('notes-insert-menu');
   for(const [label,action]of [['Imagem · Ctrl+Shift+O',()=>this.notesUpload(true)],['Arquivo · Ctrl+O',()=>this.notesUpload(false)],['Tabela · Ctrl+Alt+Q',()=>this.notesTableDialog()],['Data · Ctrl+Alt+D',()=>this.notesDateDialog()],['Vídeo do YouTube · Ctrl+Alt+V',()=>this.notesVideoDialog()]])dialog.append(button(label,label,()=>{dialog.close();action();}));
  });
 };
 p.notesTableDialog=function(){this.notesExtraDialog('Inserir tabela',dialog=>{const rows=document.createElement('input'),cols=document.createElement('input');for(const [label,input,max]of [['Linhas',rows,50],['Colunas',cols,20]]){input.type='number';input.min=1;input.max=max;input.value=3;const field=document.createElement('label');field.textContent=label;field.append(input);dialog.append(field);}dialog.append(button('Inserir tabela','Inserir',()=>{const r=Math.max(1,Math.min(50,Number(rows.value)||1)),c=Math.max(1,Math.min(20,Number(cols.value)||1)),table=document.createElement('table');table.dataset.noteTable='true';for(let i=0;i<r;i++){const tr=table.insertRow();for(let j=0;j<c;j++)tr.insertCell().append(document.createElement('br'));}dialog.close();this.notesInsertNode(table);}));});};
 p.notesDateDialog=function(){this.notesExtraDialog('Inserir data',dialog=>{const now=new Date();for(const options of [{dateStyle:'short'},{dateStyle:'long'},{dateStyle:'short',timeStyle:'short'}]){const value=new Intl.DateTimeFormat('pt-BR',options).format(now);dialog.append(button(value,value,()=>{dialog.close();this.notesInsertNode(document.createTextNode(value));}));}});};
 p.notesTemplates=function(){this.notesExtraDialog('Modelos de nota',dialog=>{
  const help=document.createElement('p');help.className='notes-template-help';help.textContent='Salve o conteúdo atual como modelo. Ao escolher um modelo, todo o texto da nota será substituído por uma cópia editável. Você pode desfazer com Ctrl+Z; editar a nota não altera o modelo salvo.';dialog.append(help);const name=document.createElement('input');name.placeholder='Nome do modelo';name.maxLength=100;dialog.append(name,button('Salvar nota como modelo','Salvar texto atual como modelo',async()=>{if(!name.value.trim())return;try{await this.notesExtraRequest('/templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.value.trim(),html:this.getCleanNotesHtml()})});dialog.close();this.notesTemplates();}catch(error){this.showToast(error.message,'error');}}));
  const list=document.createElement('div');list.textContent='Carregando modelos…';dialog.append(list);this.notesExtraRequest('/templates').then(items=>{list.replaceChildren();items.forEach(item=>list.append(button('Usar '+item.name,'Aplicar: '+item.name,async()=>{let model;try{model=await this.notesExtraRequest('/templates/'+item.id);}catch(error){this.showToast(error.message,'error');return;}this.flushNotesTyping();const template=document.createElement('template');template.innerHTML=model.html;template.content.querySelectorAll('script,style,iframe,object,embed').forEach(el=>el.remove());template.content.querySelectorAll('*').forEach(el=>[...el.attributes].forEach(attribute=>{if(/^on/i.test(attribute.name)||/^(href|src)$/i.test(attribute.name)&&/^\s*javascript:/i.test(attribute.value))el.removeAttribute(attribute.name);}));editor().replaceChildren(template.content.cloneNode(true));editor().querySelectorAll('[data-note-id]').forEach(row=>row.dataset.noteId=NotesDocument.id());this.recordNotesHistory();dialog.close();})));if(!items.length)list.textContent='Nenhum modelo salvo.';}).catch(error=>list.textContent=error.message);
 });};
 p.notesFileViewer=async function(id){
  const dialog=this.notesExtraDialog('Visualização do arquivo',dialog=>{});dialog.classList.add('notes-file-viewer');const tools=document.createElement('div');tools.className='notes-viewer-tools';const content=document.createElement('div');content.className='notes-file-page';const status=document.createElement('span');let index=0,sheet=0,column=0,total=1,info,marks=[],version=0;
  const previous=button('Página anterior','‹',()=>{if(index){index--;render();}}),next=button('Próxima página','›',()=>{if(index+1<total){index++;render();}}),expand=button('Expandir/restaurar','⛶',()=>dialog.classList.toggle('expanded')),highlight=button('Destacar seleção','Destaque',async()=>{const selection=getSelection();if(!selection.rangeCount||!content.contains(selection.anchorNode)||selection.isCollapsed)return;const range=selection.getRangeAt(0),before=document.createRange();before.selectNodeContents(content);before.setEnd(range.startContainer,range.startOffset);marks.push({start:before.toString().length,end:before.toString().length+range.toString().length});try{await this.notesExtraRequest('/files/'+id+'/annotations?page='+index,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({ranges:marks})});paint();}catch(error){this.showToast(error.message,'error');}});
  expand.innerHTML=document.getElementById('notesFullscreenBtn')?.innerHTML||'⛶';expand.onclick=()=>{expand.setAttribute('aria-expanded',String(dialog.classList.toggle('expanded')));};highlight.onmousedown=e=>e.preventDefault();tools.append(previous,status,next,highlight,expand);dialog.append(tools,content);
  const point=offset=>{const walker=document.createTreeWalker(content,NodeFilter.SHOW_TEXT);let last;while(walker.nextNode()){last=walker.currentNode;if(offset<=last.length)return [last,offset];offset-=last.length;}return last?[last,last.length]:[content,0];};
  const paint=()=>{if(!CSS.highlights)return;const h=new Highlight();for(const mark of marks){if(mark.end<=mark.start)continue;const range=document.createRange();range.setStart(...point(mark.start));range.setEnd(...point(mark.end));h.add(range);}CSS.highlights.set('notes-file-marks',h);};
  const request=path=>this.notesExtraRequest(path.replace('&','?'));
  const render=async()=>{const current=++version;content.textContent='Carregando…';try{const data=await request('/files/'+id+'/page&index='+index+'&sheet='+sheet+'&column='+column);if(current!==version||!dialog.isConnected)return;content.replaceChildren();content.style.width='';content.style.height='';
   if(info.kind==='pdf'){content.style.width=data.width+'px';content.style.height=data.height+'px';const image=document.createElement('img');image.src='/api/note-assets/files/'+id+'/page-image?user_id='+this.userId+'&index='+index;image.className='notes-pdf-image';content.append(image);for(const word of data.words){const span=document.createElement('span');span.className='notes-pdf-word';span.textContent=word.text+' ';Object.assign(span.style,{left:word.x+'px',top:word.y+'px',width:word.width+'px',height:word.height+'px',fontSize:word.height*.8+'px'});content.append(span);}}
   else if(info.kind==='word')content.innerHTML=data.html;
   else {const table=document.createElement('table');for(const row of data.rows){const tr=table.insertRow();row.forEach(value=>tr.insertCell().textContent=value);}content.append(table);if(data.more)total=index+2;}
   status.textContent=(index+1)+' / '+total;previous.disabled=index===0;next.disabled=index+1>=total;
   if(info.kind!=='sheet'){const saved=await request('/files/'+id+'/annotations&page='+index);if(current===version){marks=saved.ranges;paint();}}
  }catch(error){content.textContent=error.message;}};
  try{info=await this.notesExtraRequest('/files/'+id+'/info');dialog.querySelector('h3').textContent=info.name;total=info.pages||info.sheets?.[0]?.pages||1;highlight.hidden=info.kind==='sheet';if(info.sheets){const select=document.createElement('select');info.sheets.forEach((sheet,i)=>{const option=document.createElement('option');option.value=i;option.textContent=sheet.name;select.append(option);});select.onchange=()=>{sheet=Number(select.value);index=0;column=0;total=info.sheets[sheet].pages;render();};tools.prepend(select);tools.append(button('Colunas anteriores','‹ Colunas',()=>{if(column){column--;render();}}),button('Próximas colunas','Colunas ›',()=>{if((column+1)*100<(info.sheets[sheet].columns||100)){column++;render();}}));}await render();}catch(error){content.textContent=error.message;}
  dialog.addEventListener('close',()=>CSS.highlights?.delete('notes-file-marks'));
 };
 p.setupNotesEditing=function(){setup.call(this);if(this.notesExtrasReady)return;this.notesExtrasReady=true;const toolbar=document.getElementById('notesToolbar');
  const actions=[['divider','Divisor (Ctrl+Shift+H)','—',()=>this.notesDivider()],['link','Link (Ctrl+K)','🔗',()=>this.notesLinkDialog()],['insert','Inserir (Ctrl+Shift+I)','＋',()=>this.notesInsertMenu()],['templates','Modelos (Ctrl+Alt+M)','▤',()=>this.notesTemplates()]];
  for(const [id,label,glyph,action]of actions){const el=button(label,glyph,()=>{this.notesExtraAnchor=el;action();});el.className='toolbar-btn';if(id==='link')el.innerHTML='<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="m10 13 4-4m-6 6-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 3 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0"/></svg>';el.dataset.extra=id;el.onmousedown=e=>e.preventDefault();toolbar.append(el);}
  toolbar.querySelector('[data-command="codeBlock"]').title+=' (Ctrl+Alt+C)';toolbar.querySelector('[data-command="collapseAll"]').title+=' (Ctrl+Alt+E)';
  editor().addEventListener('keydown',e=>{const key=e.key.toLowerCase(),cell=(getSelection().anchorNode?.nodeType===3?getSelection().anchorNode.parentElement:getSelection().anchorNode)?.closest?.('td,th');
   if(cell&&editor().contains(cell)&&!e.ctrlKey&&!e.altKey){
    if(key==='tab'){e.preventDefault();e.stopImmediatePropagation();const table=cell.closest('table'),cells=[...table.querySelectorAll('td,th')];let next=cells[cells.indexOf(cell)+(e.shiftKey?-1:1)];if(!next&&!e.shiftKey){const row=table.insertRow();for(let i=0;i<cell.parentElement.cells.length;i++)row.insertCell().append(document.createElement('br'));next=row.cells[0];this.recordNotesHistory();}if(next){const range=document.createRange();range.selectNodeContents(next);range.collapse(true);getSelection().removeAllRanges();getSelection().addRange(range);this.rememberNotesSelection();}return;}
    if(key==='backspace'||key==='delete'){e.stopImmediatePropagation();return;}
    if(key==='enter'){e.preventDefault();e.stopImmediatePropagation();const range=getSelection().getRangeAt(0);range.deleteContents();const br=document.createElement('br');range.insertNode(br);if(!br.nextSibling)br.after(document.createElement('br'));range.setStartAfter(br);range.collapse(true);getSelection().removeAllRanges();getSelection().addRange(range);this.recordNotesHistory();this.rememberNotesSelection();return;}
   }
   if(key==='backspace'&&!e.ctrlKey&&!e.altKey&&this.notesBackspaceMedia()){e.preventDefault();e.stopImmediatePropagation();return;}let action;if(e.ctrlKey&&!e.altKey&&key==='k')action=()=>this.notesLinkDialog();else if(e.ctrlKey&&e.shiftKey&&key==='h')action=()=>this.notesDivider();else if(e.ctrlKey&&e.shiftKey&&key==='i')action=()=>this.notesInsertMenu();else if(e.ctrlKey&&e.shiftKey&&key==='o')action=()=>this.notesUpload(true);else if(e.ctrlKey&&!e.shiftKey&&key==='o')action=()=>this.notesUpload(false);else if(e.ctrlKey&&e.altKey){action=({c:()=>this.executeNotesCommand('codeBlock'),e:()=>this.toggleAllNotesCollapse(),m:()=>this.notesTemplates(),v:()=>this.notesVideoDialog(),q:()=>this.notesTableDialog(),d:()=>this.notesDateDialog()})[key];}else if(key==='enter'&&body(rowAt(getSelection().anchorNode))?.querySelector(':scope > hr,:scope > figure'))action=()=>{const current=rowAt(getSelection().anchorNode),next=document.createElement('div');next.className='notes-line';next.dataset.level=current.dataset.level||'0';next.innerHTML='<div class="notes-line-text"><br></div>';current.after(next);this.notesRevealInsertion(next);const range=document.createRange();range.selectNodeContents(body(next));range.collapse(true);getSelection().removeAllRanges();getSelection().addRange(range);this.recordNotesHistory();this.rememberNotesSelection();};else if(key==='backspace'&&body(rowAt(getSelection().anchorNode))?.querySelector('hr')&&!body(rowAt(getSelection().anchorNode)).textContent.trim())action=()=>this.notesDivider();if(action){e.preventDefault();e.stopImmediatePropagation();action();}},true);
  editor().addEventListener('click',e=>{const action=e.target.closest('[data-media-action]'),figure=e.target.closest('.notes-media');if(action){e.preventDefault();const row=rowAt(figure),kind=action.dataset.mediaAction;if(kind==='up'||kind==='down'){const range=document.createRange();range.selectNodeContents(body(row));range.collapse(true);getSelection().removeAllRanges();getSelection().addRange(range);this.rememberNotesSelection();this.executeNotesCommand(kind==='up'?'moveUp':'moveDown');}else{figure.style.width=Math.max(100,Math.min(editor().clientWidth-32,figure.getBoundingClientRect().width*(kind==='larger'?1.15:.85)))+'px';this.recordNotesHistory();}return;}if(figure){e.preventDefault();this.notesFocusMedia(figure);if(figure.dataset.youtube&&e.target.closest('.notes-video-play')&&!figure.querySelector('iframe')){const frame=document.createElement('iframe');frame.src='https://www.youtube-nocookie.com/embed/'+figure.dataset.youtube;frame.allowFullscreen=true;frame.allow='encrypted-media; picture-in-picture';frame.title='Vídeo do YouTube';figure.querySelector('[data-video-poster]')?.setAttribute('hidden','');figure.querySelector('.notes-video-play')?.setAttribute('hidden','');figure.prepend(frame);}return;}const link=e.target.closest('a');if(link){e.preventDefault();if(link.dataset.noteAsset){this.notesFocusMedia(link);this.notesFileViewer(link.dataset.noteAsset);}else if(safeURL(link.href))window.open(link.href,'_blank','noopener,noreferrer');}},true);
  editor().addEventListener('contextmenu',e=>{const selected=getSelection().toString().trim(),link=e.target.closest('a'),id=youtube(link?.href||selected);if(!id||!selected||link&&selected!==link.textContent.trim())return;e.preventDefault();this.rememberNotesSelection();const menu=document.createElement('div');menu.className='notes-context-menu';menu.style.left=Math.min(e.clientX,innerWidth-210)+'px';menu.style.top=Math.min(e.clientY,innerHeight-60)+'px';menu.append(button('Incorporar vídeo','Incorporar vídeo',()=>{menu.remove();this.notesMedia('video',id);}));document.body.append(menu);setTimeout(()=>document.addEventListener('pointerdown',event=>{if(!menu.contains(event.target))menu.remove();},{once:true}),0);});
  editor().addEventListener('pointerup',e=>{if(e.target.closest('.notes-media'))this.recordNotesHistory();});
  let linkTimer;document.addEventListener('input',e=>{if(!editor().contains(e.target)||e.isComposing)return;const row=rowAt(getSelection().anchorNode);clearTimeout(linkTimer);linkTimer=setTimeout(()=>{if(row?.textContent.includes('http'))this.notesAutoLinks(row);},700);},true);editor().addEventListener('paste',()=>{const session=this.notesSession;setTimeout(()=>{const candidates=[...editor().children].filter(row=>row.textContent.includes('http'));let index=0,changed=false;const process=()=>{if(this.notesSession!==session)return;const end=Math.min(index+30,candidates.length);for(;index<end;index++)changed=this.notesAutoLinks(candidates[index],false)||changed;if(index<candidates.length)setTimeout(process,0);else if(changed)this.recordNotesHistory();};process();},0);});
  let drawerAnimation;const items=[...toolbar.children],more=button('Mais ferramentas','…',()=>{
   const opening=more.getAttribute('aria-expanded')!=='true',from=drawer.hidden?0:drawer.getBoundingClientRect().height;more.setAttribute('aria-expanded',String(opening));drawerAnimation?.cancel();drawer.hidden=false;
   const to=opening?drawer.scrollHeight:0;if(matchMedia('(prefers-reduced-motion: reduce)').matches){drawer.hidden=!opening;return;}
   drawerAnimation=drawer.animate([{height:from+'px',opacity:opening?0:1},{height:to+'px',opacity:opening?1:0}],{duration:240,easing:'cubic-bezier(.22,1,.36,1)'});const animation=drawerAnimation;animation.onfinish=()=>{if(animation===drawerAnimation){drawer.hidden=!opening;drawerAnimation=null;}};
   if(opening)[...drawer.children].forEach((el,i)=>el.animate([{opacity:0,transform:'translateX(-5px)'},{opacity:1,transform:'none'}],{duration:160,delay:Math.min(i*25,200),fill:'backwards'}));
  }),drawer=document.createElement('div');more.className='toolbar-btn notes-toolbar-more';more.setAttribute('aria-expanded','false');drawer.className='notes-toolbar-overflow';drawer.hidden=true;toolbar.append(more,drawer);let widths,frame;
  const layout=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(!toolbar.clientWidth)return;if(!widths){items.forEach(el=>toolbar.insertBefore(el,more));widths=items.map(el=>el.getBoundingClientRect().width+8);}const available=toolbar.clientWidth-24;let used=0,overflow=false;items.forEach((el,i)=>{if(widths.reduce((a,b)=>a+b,0)>available&&used+widths[i]>available-36)overflow=true;(overflow?drawer:toolbar).insertBefore(el,overflow?null:more);used+=widths[i];});more.hidden=!drawer.children.length;if(more.hidden)drawer.hidden=true;});};new ResizeObserver(layout).observe(toolbar);layout();
 };
 p.refreshNotesCollapseControls=function(){refresh.call(this);for(const [command,shortcut]of [['codeBlock','Ctrl+Alt+C'],['collapseAll','Ctrl+Alt+E']]){const button=document.querySelector('[data-command="'+command+'"]');if(button){if(!button.title.includes(shortcut))button.title+=' ('+shortcut+')';button.setAttribute('aria-keyshortcuts',shortcut.replace('Ctrl','Control'));}}};
 p.getCleanNotesHtml=function(){const html=clean.call(this);if(!html.includes('<iframe'))return html;const template=document.createElement('template');template.innerHTML=html;template.content.querySelectorAll('iframe').forEach(el=>el.remove());template.content.querySelectorAll('[data-video-poster],.notes-video-play').forEach(el=>el.removeAttribute('hidden'));return template.innerHTML;};
}
